# Local development configuration
env: local

lake:
  bronze_path: "file://./data/lake/bronze"
  silver_path: "file://./data/lake/silver"
  gold_path: "file://./data/lake/gold"

# Glue configuration (not used in local)
glue:
  database: "local_dev"
  region: "us-east-1"

# EMR configuration (not used in local)
emr:
  application_id: "local-dev"

# Runtime configuration
runtime:
  shuffle_partitions: 200
  app_name: "PySparkETL-Local"

# Data quality configuration
dq:
  enabled: true
  policies_path: "conf/dq"

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  include_trace_id: true
