# AWS production configuration
env: aws

lake:
  bronze_path: "s3://${AWS_S3_BUCKET}/lake/bronze"
  silver_path: "s3://${AWS_S3_BUCKET}/lake/silver"
  gold_path: "s3://${AWS_S3_BUCKET}/lake/gold"

# Glue configuration
glue:
  database: "${AWS_GLUE_DATABASE}"
  region: "${AWS_REGION}"

# EMR Serverless configuration
emr:
  application_id: "${AWS_EMR_APPLICATION_ID}"

# Runtime configuration
runtime:
  shuffle_partitions: 200
  app_name: "PySparkETL-AWS"

# Data quality configuration
dq:
  enabled: true
  policies_path: "conf/dq"

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  include_trace_id: true
