version: 2

models:
  - name: fct_orders
    description: |
      Orders fact table with incremental processing.
      
      **Business Logic:**
      - One row per order
      - Incremental merge strategy
      - Reprocesses last 3 days to handle late-arriving data
      
      **Late Data Handling:**
      - Rolling 3-day window reprocessed on each run
      - Merge on order_id updates existing records
      - Safe for corrections and late updates
      
      **Data Contract:**
      - Primary Key: order_id
      - Foreign Keys: customer_id, product_id
      - No nullable keys
      
      **Owner:** Data Engineering Team
      **SLA:** Hourly refresh
      **Breaking Changes:** Require 1-week notice
    
    columns:
      - name: order_id
        description: "Unique order identifier (PK)"
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: "FK to dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      
      - name: product_id
        description: "FK to dim_product"
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
      
      - name: order_date
        description: "Date order was placed"
        tests:
          - not_null
      
      - name: total_amount
        description: "Order total amount (USD)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: updated_at
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      
      - name: order_month
        description: "Order month (for partitioning/aggregation)"
        tests:
          - not_null
      
      - name: order_quarter
        description: "Order quarter (for reporting)"
        tests:
          - not_null
      
      - name: order_year
        description: "Order year (for partitioning)"
        tests:
          - not_null
      
      - name: customer_segment
        description: "Customer segment at time of order"
      
      - name: product_category
        description: "Product category at time of order"
      
      - name: estimated_margin
        description: "Estimated profit margin (USD)"
