input:
  customer_path: data/input_data/customers.csv
  product_path: data/input_data/products.csv
  orders_path: data/input_data/orders.json
  returns_path: data/input_data/returns.json
  exchange_rates_path: data/input_data/exchange_rates.csv
  inventory_path: data/input_data/inventory_snapshots.csv
  customers_changes_path: data/input_data/customers_changes.csv
  orders_stream_path: data/stream/orders

streaming:
  enable: true
  checkpoints:
    orders_bronze: data/checkpoints/orders_bronze
    fact_orders: data/checkpoints/fact_orders
  watermark: "10 minutes"
  
  # Kafka configuration
  kafka:
    enable: true
    bootstrap_servers: "${ENV:KAFKA_BOOTSTRAP_SERVERS}"
    topic: "${ENV:KAFKA_TOPIC}"
    starting_offsets: "earliest"
    max_offsets_per_trigger: 1000
    fail_on_data_loss: false
    
  # Event Hub configuration (Azure alternative)
  event_hub:
    enable: false
    connection_string: "${SECRET:eventhub:connection_string}"
    consumer_group: "$Default"
    starting_position: "latest"

output:
  parquet_path: data/output_data/final.parquet
  delta_path: data/output_data/final_delta
  bronze_path: data/lakehouse/bronze
  silver_path: data/lakehouse/silver
  gold_path: data/lakehouse/gold

spark:
  app_name: "PDEInterviewPipeline"
  shuffle_partitions: 8

dq_rules:
  min_age: 18
  max_age: 99
  email_regex: "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"

maintenance:
  enable: false
  log_retention: "7 days"
  vacuum_retain: "168"

# Azure configuration for enterprise features
azure:
  subscription_id: "${ENV:AZURE_SUBSCRIPTION_ID}"
  resource_group: "${ENV:AZURE_RESOURCE_GROUP}"
  workspace_name: "${ENV:AZURE_WORKSPACE_NAME}"
  compliance_standards: ["gdpr", "hipaa", "sox"]
  key_vault_name: "${ENV:AZURE_KEY_VAULT_NAME}"
  storage_account_name: "${ENV:AZURE_STORAGE_ACCOUNT_NAME}"

# Governance configuration
governance:
  catalog_name: "main"
  schema_name: "data_engineering"
  policies:
    - name: "data_retention"
      description: "Data retention policy"
      rules: ["Delete data older than 7 years"]
    - name: "data_access"
      description: "Data access control"
      rules: ["Role-based access control"]

# Disaster recovery configuration
disaster_recovery:
  primary_region: "${ENV:AZURE_PRIMARY_REGION}"
  secondary_region: "${ENV:AZURE_SECONDARY_REGION}"
  enable_cross_region_replication: true
  storage_accounts: ["${ENV:AZURE_PRIMARY_STORAGE}", "${ENV:AZURE_SECONDARY_STORAGE}"]
  tables_to_backup: ["customers", "orders", "products"]
  recovery_tier: "business_critical"

# Data quality configuration
data_quality:
  enabled: true
  severity_levels: ["critical", "warning", "info"]
  auto_fix: false
  alerting: true

# Monitoring configuration
monitoring:
  enabled: true
  metrics_collection: true
  alerting: true
  dashboard_url: "${ENV:MONITORING_DASHBOARD_URL}"
