# Delta Lake Data Retention Configuration

# Retention policies for different data layers
retention_policies:
  bronze:
    retention_days: 90          # Keep raw data for 90 days
    vacuum_retain_hours: 720    # Keep files for 30 days
    description: "Raw data - keep longer for debugging"
    
  silver:
    retention_days: 60          # Keep cleansed data for 60 days
    vacuum_retain_hours: 336    # Keep files for 14 days
    description: "Cleansed data - medium term retention"
    
  gold:
    retention_days: 365         # Keep analytics data for 1 year
    vacuum_retain_hours: 168    # Keep files for 7 days
    description: "Analytics data - long term retention"

# Date-based cleanup settings
date_cleanup:
  orders:
    partition_column: "order_date"
    retention_days: 30
    date_format: "yyyy-MM-dd"
    
  customers:
    partition_column: "registration_date"
    retention_days: 90
    date_format: "yyyy-MM-dd"
    
  products:
    partition_column: "launch_date"
    retention_days: 180
    date_format: "yyyy-MM-dd"

# Maintenance schedule
maintenance:
  frequency: "daily"           # daily, weekly, monthly
  optimize_tables: true
  vacuum_tables: true
  cleanup_old_partitions: true
  set_retention_policies: true

# Performance optimization
optimization:
  zorder_columns:
    orders: ["customer_id", "product_id", "order_date"]
    fact_orders: ["customer_id", "product_id", "order_ym"]
    customers: ["customer_id", "region"]
    products: ["product_id", "category"]

# Specific date ranges for cleanup (optional)
date_ranges:
  historical_cleanup:
    - table: "data/lakehouse/silver/orders_cleansed"
      date_column: "order_date"
      start_date: "2020-01-01"
      end_date: "2022-12-31"
      description: "Remove very old historical data"
