"""
Project A Schemas

Explicit schemas for all data sources.
"""

from .bronze_schemas import (
    CRM_ACCOUNTS_SCHEMA,
    CRM_CONTACTS_SCHEMA,
    CRM_OPPORTUNITIES_SCHEMA,
    FX_RATES_SCHEMA,
    KAFKA_EVENTS_SCHEMA,
    REDSHIFT_BEHAVIOR_SCHEMA,
    SNOWFLAKE_CUSTOMERS_SCHEMA,
    SNOWFLAKE_ORDERS_SCHEMA,
    SNOWFLAKE_PRODUCTS_SCHEMA,
)

__all__ = [
    "CRM_ACCOUNTS_SCHEMA",
    "CRM_CONTACTS_SCHEMA",
    "CRM_OPPORTUNITIES_SCHEMA",
    "REDSHIFT_BEHAVIOR_SCHEMA",
    "SNOWFLAKE_CUSTOMERS_SCHEMA",
    "SNOWFLAKE_ORDERS_SCHEMA",
    "SNOWFLAKE_PRODUCTS_SCHEMA",
    "FX_RATES_SCHEMA",
    "KAFKA_EVENTS_SCHEMA",
]
