version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
loggers:
  pyspark_interview_project:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]

