input:
  customer_path: data/input_data/customers.csv
  product_path: data/input_data/products.csv
  orders_path: data/input_data/orders.json
  returns_path: data/input_data/returns.json
  exchange_rates_path: data/input_data/exchange_rates.csv
  inventory_path: data/input_data/inventory_snapshots.csv
  customers_changes_path: data/input_data/customers_changes.csv
  orders_stream_path: data/stream/orders

streaming:
  enable: false
  checkpoints:
    orders_bronze: data/checkpoints/orders_bronze
    fact_orders: data/checkpoints/fact_orders
  watermark: "10 minutes"

output:
  parquet_path: data/output_data/final.parquet
  delta_path: data/output_data/final_delta
  bronze_path: data/lakehouse/bronze
  silver_path: data/lakehouse/silver
  gold_path: data/lakehouse/gold

spark:
  app_name: "PDEInterviewPipeline-Azure-Staging"
  shuffle_partitions: 16

dq_rules:
  min_age: 18
  max_age: 99
  email_regex: "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"

maintenance:
  enable: false
  log_retention: "7 days"
  vacuum_retain: "168"

